import './globals.css'
import Footer from './scenes/globals/Footer'
import NavBar from './scenes/globals/NavBar'


export const metadata = {
  title: 'Msader Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body >
      <NavBar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
